// template/components/cmsbar/CmsBar.tsx
"use client";
import { PREVIEW_LS_KEY } from "@/lib/cmsbar/keys";

import { useEffect, useRef, useState } from "react";
import { useHost } from "./host";
import { cmsConfig } from "@/cms.config";
import { publishingMode } from "@/lib/cmsbar/config";
import { useCms } from "./ContentProvider";
import { VersionsDialog } from "./VersionsDialog";
import { PageMetaDrawer } from "./PageMetaDrawer";
import { SettingsDrawer } from "./SettingsDrawer";
import { IssuesButton } from "./IssuesButton";
import { CmsTour, TOUR_OPEN_EVENT } from "./CmsTour";
import { pageNameForPath } from "./pageName";
import { cn } from "@/lib/cmsbar/utils";
import { cmsFetch } from "@/lib/cmsbar/cmsFetch";

const DIVIDER = <span className="h-4 w-px bg-white/20" />;

// Guided tour is opt-in: sites without `tour` config get no button, no overlay.
const TOUR_ENABLED = (cmsConfig.tour?.steps.length ?? 0) > 0;

// Direct publishing: saves go straight to the base branch - no draft branch,
// no PR, no approval flow. Review-flow affordances are hidden.
const DIRECT = publishingMode(cmsConfig) === "direct";

const TourButton = () =>
  TOUR_ENABLED ? (
    <button
      onClick={() => window.dispatchEvent(new CustomEvent(TOUR_OPEN_EVENT))}
      className="rounded-full bg-white/10 hover:bg-white/20 text-xs px-3 py-1"
      title="Replay the guided tour"
    >
      ✦ Guide
    </button>
  ) : null;

export function CmsBar() {
  const {
    cms,
    pendingCount,
    pendingEdits,
    pendingUploads,
    pendingFolders,
    pendingDeletes,
    discardAll,
    applyCommitted,
    setPreview,
  } = useCms();
  const { pathname, navigate } = useHost();
  const [busy, setBusy] = useState<"saving" | "starting" | null>(null);
  const [error, setError] = useState<string | null>(null);
  // Transient in-bar confirmation after a direct publish (auto-clears).
  const [notice, setNotice] = useState<string | null>(null);
  const noticeTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const [versionsOpen, setVersionsOpen] = useState(false);
  const [metaOpen, setMetaOpen] = useState(false);
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [highlightShared, setHighlightShared] = useState(false);

  // Toggle the body class that lights up every shared element on the page, so
  // an editor can see at a glance what ripples site-wide before touching it.
  useEffect(() => {
    document.body.classList.toggle("cms-highlight-shared", highlightShared);
    return () => document.body.classList.remove("cms-highlight-shared");
  }, [highlightShared]);

  useEffect(
    () => () => {
      if (noticeTimer.current) clearTimeout(noticeTimer.current);
    },
    [],
  );

  const flashNotice = (msg: string) => {
    setNotice(msg);
    if (noticeTimer.current) clearTimeout(noticeTimer.current);
    noticeTimer.current = setTimeout(() => setNotice(null), 6000);
  };

  const startDraft = async () => {
    setBusy("starting");
    setError(null);
    try {
      const title = pageNameForPath(pathname);
      const res = await cmsFetch("/session/start", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ title, pagePath: pathname }),
      });
      if (!res.ok) {
        const b = (await res.json().catch(() => ({}))) as { error?: string };
        throw new Error(b.error || `HTTP ${res.status}`);
      }
      window.location.reload();
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
      setBusy(null);
    }
  };

  const forkDraft = async (
    fromBranch: string,
    fromTitle: string | undefined,
  ) => {
    setBusy("starting");
    setError(null);
    try {
      const base = fromTitle?.trim() || pageNameForPath(pathname);
      const title = /\(fork\)$/i.test(base) ? base : `${base} (fork)`;
      const res = await cmsFetch("/session/fork", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ fromBranch, title }),
      });
      if (!res.ok) {
        const b = (await res.json().catch(() => ({}))) as { error?: string };
        throw new Error(b.error || `HTTP ${res.status}`);
      }
      window.location.reload();
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
      setBusy(null);
    }
  };

  if (!cms.authenticated) return null;

  const logout = async () => {
    await cmsFetch("/logout", { method: "POST" });
    window.location.reload();
  };

  const exitDraft = async () => {
    if (
      pendingCount > 0 &&
      !confirm("Discard pending changes and exit this draft?")
    )
      return;
    discardAll();
    await cmsFetch("/session/clear", { method: "POST" });
    try {
      localStorage.removeItem(PREVIEW_LS_KEY);
    } catch {
      /* SSR */
    }
    window.location.reload();
  };

  const save = async () => {
    if (pendingCount === 0 || !cms.draft) return;
    setBusy("saving");
    setError(null);
    try {
      const uploads = await Promise.all(
        pendingUploads.map(async (u) => ({
          repoPath: u.repoPath,
          contentBase64: await fileToBase64(u.file),
        })),
      );
      const res = await cmsFetch("/commit", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({
          edits: pendingEdits,
          uploads,
          folders: pendingFolders,
          deletes: pendingDeletes,
        }),
      });
      if (!res.ok) {
        const b = (await res.json().catch(() => ({}))) as { error?: string };
        if (res.status === 401) {
          // A 12h session can lapse mid-edit (most likely in direct mode, where
          // the rolling-refresh poll is skipped). Make the recovery obvious and
          // reassure that work isn't lost - pending edits are kept on this
          // device and reattach to the next session after logging back in.
          throw new Error(
            "Your session expired - log in again at /cmsbar/login, then your edits are still here. Your unsaved changes are kept on this device.",
          );
        }
        throw new Error(b.error || `Save failed (HTTP ${res.status})`);
      }
      const result = (await res.json()) as {
        direct?: boolean;
        branch?: string;
        commitSha?: string;
        prUrl?: string;
        prError?: string;
        branchUrl?: string;
      };
      if (result.direct) {
        // Direct publish: the commit already landed on the live branch.
        // Stay in edit mode - there is no PR to review and no draft branch
        // to preview - and confirm inline. The server reports the branch it
        // committed to (a stale review-era cookie can carry a cms/* name).
        applyCommitted();
        flashNotice(
          `Published - the site redeploys from ${result.branch ?? "the live branch"}`,
        );
        return;
      }
      applyCommitted({ prUrl: result.prUrl });
      // After a successful save, switch into preview mode against the just-saved
      // branch - so the editor immediately sees the rendered result without the
      // dashed editing outlines, and can't accidentally start another round of
      // edits before deciding what's next.
      if (cms.draft) {
        void setPreview({
          branch: cms.draft.branch,
          title: cms.draft.title,
        });
      }
      if (result.prError) {
        setError(
          `Commit succeeded but PR creation failed: ${result.prError}. Branch URL: ${result.branchUrl}`,
        );
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setBusy(null);
    }
  };

  // ─── Preview banner ───────────────────────────────────────────────────────
  if (cms.preview) {
    return (
      <>
        <PreviewBanner
          title={cms.preview.title ?? cms.preview.branch}
          approved={!!cms.preview.approved}
          onExitPreview={() => setPreview(null)}
          onEdit={async () => {
            const res = await cmsFetch("/session/switch", {
              method: "POST",
              headers: { "content-type": "application/json" },
              body: JSON.stringify({
                branch: cms.preview!.branch,
                title: cms.preview!.title,
              }),
            });
            const data = (await res.json().catch(() => ({}))) as {
              pagePath?: string;
            };
            try {
              localStorage.removeItem(PREVIEW_LS_KEY);
            } catch {
              /* SSR */
            }
            const target = data.pagePath;
            if (target && target !== pathname) {
              window.location.href = target;
            } else {
              window.location.reload();
            }
          }}
          onFork={() => forkDraft(cms.preview!.branch, cms.preview!.title)}
          onShowVersions={() => setVersionsOpen(true)}
          onLogout={logout}
        />
        {versionsOpen && (
          <VersionsDialog
            onClose={() => setVersionsOpen(false)}
            onFork={(branch, title) => {
              setVersionsOpen(false);
              forkDraft(branch, title);
            }}
          />
        )}
        {/* Saving a draft lands here (preview); the tour remounts and
            resumes its step from sessionStorage, so render it here too. */}
        {TOUR_ENABLED && <CmsTour />}
      </>
    );
  }

  // ─── No active draft ──────────────────────────────────────────────────────
  if (!cms.draft) {
    return (
      <>
        <div
          data-cms-bar
          className="fixed bottom-4 left-1/2 -translate-x-1/2 z-[100] flex items-center gap-3 rounded-full bg-slate-900/95 text-white px-4 py-2 shadow-2xl backdrop-blur text-sm"
        >
          <span className="font-medium">CMSBar</span>
          <span className="rounded-full bg-emerald-500/20 text-emerald-200 px-2.5 py-0.5 text-xs font-medium">
            Live site
          </span>
          {DIVIDER}
          <button
            onClick={startDraft}
            disabled={busy === "starting"}
            className="rounded-full bg-[var(--cmsbar-accent)] hover:bg-[var(--cmsbar-accent-strong)] text-white text-xs font-semibold px-3 py-1 disabled:opacity-60"
            title={
              DIRECT
                ? "Direct publishing: saves commit straight to the live branch"
                : `Will create a draft named "${pageNameForPath(pathname)}"`
            }
          >
            {busy === "starting"
              ? "Starting…"
              : DIRECT
                ? "Edit site"
                : "New draft"}
          </button>
          {/* Versions lists open cms/* PRs; direct publishing creates none,
              so the dialog would be perpetually empty - hide it. */}
          {!DIRECT && (
            <button
              onClick={() => setVersionsOpen(true)}
              className="rounded-full bg-white/10 hover:bg-white/20 text-xs px-3 py-1"
            >
              Versions
            </button>
          )}
          <TourButton />
          {DIVIDER}
          <button
            onClick={() => setMetaOpen(true)}
            className="rounded-full bg-white/10 hover:bg-white/20 text-xs px-3 py-1"
            title="Preview SEO / page metadata (read-only without a draft)"
          >
            🔎 Page meta
          </button>
          <button
            onClick={() => setSettingsOpen(true)}
            className="rounded-full bg-white/10 hover:bg-white/20 text-xs px-3 py-1"
            title="Preview site settings (read-only without a draft)"
          >
            ⚙️ Settings
          </button>
          {DIVIDER}
          <IssuesButton />
          {DIVIDER}
          <button
            onClick={logout}
            className="rounded-full bg-white/10 hover:bg-white/20 px-3 py-1 text-xs"
          >
            Log out
          </button>
        </div>
        {versionsOpen && (
          <VersionsDialog
            onClose={() => setVersionsOpen(false)}
            onFork={(branch, title) => {
              setVersionsOpen(false);
              forkDraft(branch, title);
            }}
          />
        )}
        {metaOpen && (
          <PageMetaDrawer onClose={() => setMetaOpen(false)} canEdit={false} />
        )}
        {settingsOpen && (
          <SettingsDrawer
            onClose={() => setSettingsOpen(false)}
            canEdit={false}
          />
        )}
        {TOUR_ENABLED && <CmsTour />}
      </>
    );
  }

  // ─── Active draft ─────────────────────────────────────────────────────────
  // The approval lock is a review-flow concept; in direct mode there is no PR
  // to approve, so it must never render (or block saving).
  const approved = !DIRECT && !!cms.draftApproved;
  const stripBg = approved
    ? "bg-emerald-600 text-white"
    : pendingCount > 0
      ? "bg-[var(--cmsbar-accent)] text-white"
      : "bg-[var(--cmsbar-accent)] text-white";
  return (
    <>
      {/* Always-on top strip so the editor can't lose track of being in draft mode. */}
      <div
        className={cn(
          "fixed top-0 left-0 right-0 z-[99] text-xs font-medium shadow flex items-center justify-center gap-3 px-4 py-1.5",
          stripBg,
        )}
      >
        <span>
          {approved
            ? "Approved draft (read-only):"
            : DIRECT
              ? "Editing live site:"
              : "Editing draft:"}
        </span>
        <strong className="truncate max-w-[24rem]">{cms.draft.title}</strong>
        {!approved && pendingCount > 0 && (
          <span className="rounded-full bg-white/20 text-white text-[10px] px-2 py-0.5">
            {pendingCount} unsaved
          </span>
        )}
        {approved && (
          <span className="rounded-full bg-emerald-900/40 text-emerald-100 text-[10px] px-2 py-0.5">
            label · {cms.approvedLabelName ?? "cmsbar approved"}
          </span>
        )}
        {cms.draft.pagePath && cms.draft.pagePath !== pathname && (
          <button
            onClick={() => navigate(cms.draft!.pagePath!)}
            className="rounded-full bg-white/20 hover:bg-white/30 text-white text-[10px] px-2 py-0.5 underline decoration-dotted underline-offset-2"
            title={`This draft was started on ${cms.draft.pagePath}. Click to navigate there.`}
          >
            ⚠ Go to {pageNameForPath(cms.draft.pagePath)}
          </button>
        )}
      </div>

      {error && (
        <div className="fixed bottom-20 left-1/2 -translate-x-1/2 z-[110] max-w-md bg-red-600 text-white text-sm rounded-lg shadow-lg px-4 py-2 flex items-start gap-3">
          <div className="flex-1 break-all">{error}</div>
          <button
            onClick={() => setError(null)}
            className="text-white/80 hover:text-white"
          >
            ✕
          </button>
        </div>
      )}
      <div
        data-cms-bar
        className="fixed bottom-4 left-1/2 -translate-x-1/2 z-[100] flex items-center gap-3 rounded-full bg-slate-900/95 text-white px-4 py-2 shadow-2xl backdrop-blur text-sm"
      >
        <span className="font-medium">CMSBar</span>
        <span
          className={cn(
            "rounded-full px-2.5 py-0.5 text-xs font-medium",
            approved
              ? "bg-emerald-500/20 text-emerald-200"
              : DIRECT
                ? "bg-amber-500/20 text-amber-200"
                : "bg-[var(--cmsbar-accent-soft)] text-[var(--cmsbar-accent-text)]",
          )}
          title={
            DIRECT
              ? "Direct publishing: edits commit straight to the live branch - no review"
              : undefined
          }
        >
          {approved ? "Approved" : DIRECT ? "Direct" : "Draft"}
        </span>
        <span
          className="text-white/50 text-xs max-w-[12rem] truncate"
          title={cms.draft.title}
        >
          {cms.draft.title}
        </span>
        {DIVIDER}

        {/* 1. Save (or Fork when the draft is approved/locked) */}
        {approved ? (
          <button
            onClick={() => forkDraft(cms.draft!.branch, cms.draft!.title)}
            disabled={busy === "starting"}
            className="rounded-full bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-semibold px-3 py-1 disabled:opacity-60"
            title="This draft is locked - fork it to keep editing"
          >
            {busy === "starting" ? "Forking…" : "Fork"}
          </button>
        ) : (
          <button
            onClick={save}
            disabled={pendingCount === 0 || busy !== null}
            className="rounded-full bg-[var(--cmsbar-accent)] hover:bg-[var(--cmsbar-accent-strong)] text-white text-xs font-semibold px-3 py-1 disabled:opacity-40 disabled:cursor-not-allowed"
            title={
              pendingCount === 0
                ? "No changes to save"
                : DIRECT
                  ? `Publish ${pendingCount} change(s) straight to the live branch`
                  : `Save ${pendingCount} change(s)`
            }
          >
            {busy === "saving"
              ? DIRECT
                ? "Publishing…"
                : "Saving…"
              : DIRECT
                ? "Publish"
                : "Save"}
          </button>
        )}
        {notice && (
          <span
            className="text-emerald-300 text-xs max-w-[18rem] truncate"
            title={notice}
          >
            ✓ {notice}
          </span>
        )}
        {/* 2. Discard draft (abandon the whole draft and return to the live site) */}
        <button
          onClick={exitDraft}
          className="rounded-full bg-white/10 hover:bg-white/20 text-xs px-3 py-1"
          title="Discard this draft and return to the live site"
        >
          Discard draft
        </button>

        {DIVIDER}

        {/* 4. Page meta · 5. Settings */}
        <button
          onClick={() => setMetaOpen(true)}
          className="rounded-full bg-white/10 hover:bg-white/20 text-xs px-3 py-1"
          title={
            approved
              ? "View SEO / page metadata (read-only)"
              : "Edit SEO / page metadata"
          }
        >
          🔎 Page meta
        </button>
        <button
          onClick={() => setSettingsOpen(true)}
          className="rounded-full bg-white/10 hover:bg-white/20 text-xs px-3 py-1"
          title="Site settings (workshop visibility & schedule)"
        >
          ⚙️ Settings
        </button>

        {DIVIDER}

        {/* Issue reporting + shared-element highlight */}
        <IssuesButton />
        <button
          onClick={() => setHighlightShared((v) => !v)}
          className={cn(
            "rounded-full text-xs px-3 py-1",
            highlightShared
              ? "bg-[var(--cmsbar-shared-soft)] text-[var(--cmsbar-shared-text)]"
              : "bg-white/10 hover:bg-white/20",
          )}
          title="Highlight every element that appears on more than one page"
        >
          🔗 Shared
        </button>
        <TourButton />

        {DIVIDER}

        {/* 7. Log out */}
        <button
          onClick={logout}
          className="rounded-full bg-white/10 hover:bg-white/20 px-3 py-1 text-xs"
        >
          Log out
        </button>
      </div>
      {versionsOpen && (
        <VersionsDialog
          onClose={() => setVersionsOpen(false)}
          onFork={(branch, title) => {
            setVersionsOpen(false);
            forkDraft(branch, title);
          }}
        />
      )}
      {metaOpen && (
        <PageMetaDrawer
          onClose={() => setMetaOpen(false)}
          canEdit={!approved}
        />
      )}
      {settingsOpen && (
        <SettingsDrawer
          onClose={() => setSettingsOpen(false)}
          canEdit={!approved}
        />
      )}
      {TOUR_ENABLED && <CmsTour />}
    </>
  );
}

function PreviewBanner({
  title,
  approved,
  onExitPreview,
  onEdit,
  onFork,
  onShowVersions,
  onLogout,
}: {
  title: string;
  approved: boolean;
  onExitPreview: () => void;
  onEdit: () => void;
  onFork: () => void;
  onShowVersions: () => void;
  onLogout: () => void;
}) {
  return (
    <>
      {/* Banner across the top of the page so the editor can never miss they're previewing. */}
      <div className="fixed top-0 left-0 right-0 z-[100] bg-amber-500 text-amber-950 text-sm font-medium shadow flex items-center justify-center gap-3 px-4 py-2">
        <span>Previewing draft:</span>
        <strong className="truncate max-w-[24rem]">{title}</strong>
        {approved && (
          <span className="rounded-full bg-emerald-700 text-white text-xs px-2 py-0.5">
            approved - read-only
          </span>
        )}
        <button
          onClick={onExitPreview}
          className="ml-3 underline decoration-dotted"
        >
          Exit preview
        </button>
      </div>
      <div
        data-cms-bar
        className="fixed bottom-4 left-1/2 -translate-x-1/2 z-[100] flex items-center gap-3 rounded-full bg-slate-900/95 text-white px-4 py-2 shadow-2xl backdrop-blur text-sm"
      >
        <span className="font-medium">CMSBar</span>
        <span className="rounded-full bg-amber-500/20 text-amber-200 px-2.5 py-0.5 text-xs font-medium">
          Preview
        </span>
        {DIVIDER}
        {!approved && (
          <button
            onClick={onEdit}
            className="rounded-full bg-[var(--cmsbar-accent)] hover:bg-[var(--cmsbar-accent-strong)] text-white text-xs font-semibold px-3 py-1"
            title="Switch your active draft to this PR and continue editing it"
          >
            Edit this version
          </button>
        )}
        <button
          onClick={onExitPreview}
          className="rounded-full bg-white/10 hover:bg-white/20 text-xs px-3 py-1"
        >
          Exit preview
        </button>
        <button
          onClick={onFork}
          className="rounded-full bg-white/10 hover:bg-white/20 text-xs px-3 py-1"
          title="Create a new draft branched from this one"
        >
          Fork
        </button>
        <button
          onClick={onShowVersions}
          className="rounded-full bg-white/10 hover:bg-white/20 text-xs px-3 py-1"
        >
          Versions
        </button>
        {DIVIDER}
        <IssuesButton />
        {DIVIDER}
        <button
          onClick={onLogout}
          className="rounded-full bg-white/10 hover:bg-white/20 px-3 py-1 text-xs"
        >
          Log out
        </button>
      </div>
    </>
  );
}

function fileToBase64(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => {
      const result = reader.result as string;
      const i = result.indexOf(",");
      resolve(i >= 0 ? result.slice(i + 1) : result);
    };
    reader.onerror = () => reject(reader.error);
    reader.readAsDataURL(file);
  });
}

// examples/sveltekit/src/cmsbar/CmsBar.svelte
<script lang="ts">
  // The editor bar, ported from template/components/cmsbar/CmsBar.tsx to
  // Svelte 5. S2 ported the core edit loop; S5 wires in the remaining
  // drawers/panels - Versions, Issues (with a per-page open-count badge),
  // Settings, Page meta, and the opt-in guided Tour - matching CmsBar.tsx's
  // layout and conditions (Versions hidden in direct mode; the Tour button only
  // when cmsConfig.tour has steps; the shared-highlight toggle in draft mode).
  //
  // States:
  //   - !authenticated  -> inline login form (POST /login, then full reload so
  //                        the server re-reads the fresh session cookie).
  //   - preview         -> read-only preview banner + bar (review-flow Save
  //                        lands here against the just-saved branch).
  //   - authenticated, no draft -> "Live site" bar with Edit/New-draft.
  //   - authenticated, active draft -> top strip + bar with Save + Discard,
  //                        pendingCount, the direct "Published" notice, errors,
  //                        and the 401 "session expired" recovery message.
  //
  // Direct vs review publishing changes the verbs and the post-Save behaviour,
  // exactly as in CmsBar.tsx.

  import { getCmsContext } from "@/cmsbar/content.svelte";
  import { cmsFetch } from "@/lib/cmsbar/cmsFetch";
  import { PREVIEW_LS_KEY } from "@/lib/cmsbar/keys";
  import { cmsConfig } from "@/cms.config";
  import { publishingMode } from "@/lib/cmsbar/config";
  import { pageNameForPath } from "@/lib/cmsbar/pageName";
  import {
    visibleOnPage,
    type ParsedIssue,
  } from "@/lib/cmsbar/backend/issues";
  import { page } from "$app/state";
  import VersionsDialog from "@/cmsbar/VersionsDialog.svelte";
  import PageMetaDrawer from "@/cmsbar/PageMetaDrawer.svelte";
  import SettingsDrawer from "@/cmsbar/SettingsDrawer.svelte";
  import IssuesPanel from "@/cmsbar/IssuesPanel.svelte";
  import CmsTour, { TOUR_OPEN_EVENT } from "@/cmsbar/CmsTour.svelte";

  const store = getCmsContext();

  // Direct publishing: saves commit straight to the base branch - no draft
  // branch, no PR, no preview. Review-flow affordances are hidden.
  const DIRECT = publishingMode(cmsConfig) === "direct";
  // Guided tour is opt-in: sites without `tour` config get no button, no overlay.
  const TOUR_ENABLED = (cmsConfig.tour?.steps.length ?? 0) > 0;


  // Reactive current path (matches React's useHost().pathname). Falls back to
  // "/" during SSR before $app/state is populated.
  const pathname = $derived(page.url?.pathname ?? "/");

  // Reactive store reads.
  const cms = $derived(store.cms);
  const pendingCount = $derived(store.pendingCount);

  let busy = $state<"saving" | "starting" | null>(null);
  let error = $state<string | null>(null);
  // Transient confirmation after a direct publish (auto-clears).
  let notice = $state<string | null>(null);
  let noticeTimer: ReturnType<typeof setTimeout> | null = null;

  // Drawer/panel open flags.
  let versionsOpen = $state(false);
  let metaOpen = $state(false);
  let settingsOpen = $state(false);
  let highlightShared = $state(false);

  // Login form state.
  let username = $state("");
  let password = $state("");
  let loginError = $state<string | null>(null);
  let loginBusy = $state(false);

  // Toggle the body class that lights up every shared element on the page, so
  // an editor can see at a glance what ripples site-wide before touching it.
  $effect(() => {
    document.body.classList.toggle("cms-highlight-shared", highlightShared);
    return () => document.body.classList.remove("cms-highlight-shared");
  });

  $effect(() => () => {
    if (noticeTimer) clearTimeout(noticeTimer);
  });

  function flashNotice(msg: string) {
    notice = msg;
    if (noticeTimer) clearTimeout(noticeTimer);
    noticeTimer = setTimeout(() => (notice = null), 6000);
  }

  // ── Issues button state (owned here, mirroring IssuesButton.tsx) ──────────
  // Lives in the bar so the per-page open-count badge and the panel share one
  // list. GitHub's label-filtered list can lag seconds behind a create, so
  // keep just-created issues pinned until a reload sees them.
  let issuesOpen = $state(false);
  let issues = $state<ParsedIssue[]>([]);
  let issuesLoading = $state(false);
  let issuesRefreshing = $state(false);
  let issuesError = $state<string | null>(null);
  let issuesLoadedOnce = $state(false);
  const pendingIssueNums = new Set<number>();
  let issuesInitialLoadDone = false;

  function mergeWithPending(
    fetched: ParsedIssue[],
    prev: ParsedIssue[],
  ): ParsedIssue[] {
    const fetchedNums = new Set(fetched.map((i) => i.number));
    for (const n of fetchedNums) pendingIssueNums.delete(n);
    const extra = prev.filter(
      (i) => pendingIssueNums.has(i.number) && !fetchedNums.has(i.number),
    );
    return [...extra, ...fetched];
  }

  function addIssue(issue: ParsedIssue) {
    pendingIssueNums.add(issue.number);
    const rest = issues.filter((i) => i.number !== issue.number);
    issues = [issue, ...rest];
  }

  async function reloadIssues() {
    if (!issuesInitialLoadDone) issuesLoading = true;
    else issuesRefreshing = true;
    issuesError = null;
    try {
      const res = await cmsFetch("/issues", { cache: "no-store" });
      if (!res.ok) {
        const b = (await res.json().catch(() => ({}))) as { error?: string };
        throw new Error(b.error || `HTTP ${res.status}`);
      }
      const data = (await res.json()) as { issues: ParsedIssue[] };
      issues = mergeWithPending(data.issues, issues);
    } catch (e) {
      issuesError = e instanceof Error ? e.message : String(e);
    } finally {
      issuesLoading = false;
      issuesRefreshing = false;
      issuesInitialLoadDone = true;
      issuesLoadedOnce = true;
    }
  }

  // Fetch once on mount for the badge count (authenticated editors only).
  $effect(() => {
    if (!store.cms.authenticated) return;
    void reloadIssues();
  });

  const issuesCount = $derived(
    issuesLoadedOnce
      ? issues.filter(
          (i) => i.status !== "closed" && visibleOnPage(i, pathname),
        ).length
      : 0,
  );

  function openIssues() {
    issuesOpen = true;
    void reloadIssues();
  }

  function openTour() {
    window.dispatchEvent(new CustomEvent(TOUR_OPEN_EVENT));
  }

  async function login(e: Event) {
    e.preventDefault();
    loginError = null;
    loginBusy = true;
    try {
      const res = await cmsFetch("/login", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ username, password }),
      });
      if (!res.ok) {
        const body = (await res.json().catch(() => ({}))) as { error?: string };
        loginError = body.error || "Login failed";
        loginBusy = false;
        return;
      }
      // Full-page navigation so the server re-reads the new session cookie.
      window.location.assign(pathname);
    } catch (err) {
      loginError = String(err);
      loginBusy = false;
    }
  }

  async function logout() {
    await cmsFetch("/logout", { method: "POST" });
    window.location.reload();
  }

  async function startDraft() {
    busy = "starting";
    error = null;
    try {
      const title = pageNameForPath(pathname);
      const res = await cmsFetch("/session/start", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ title, pagePath: pathname }),
      });
      if (!res.ok) {
        const b = (await res.json().catch(() => ({}))) as { error?: string };
        throw new Error(b.error || `HTTP ${res.status}`);
      }
      window.location.reload();
    } catch (e) {
      error = e instanceof Error ? e.message : String(e);
      busy = null;
    }
  }

  async function forkDraft(fromBranch: string, fromTitle: string | undefined) {
    busy = "starting";
    error = null;
    try {
      const base = fromTitle?.trim() || pageNameForPath(pathname);
      const title = /\(fork\)$/i.test(base) ? base : `${base} (fork)`;
      const res = await cmsFetch("/session/fork", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ fromBranch, title }),
      });
      if (!res.ok) {
        const b = (await res.json().catch(() => ({}))) as { error?: string };
        throw new Error(b.error || `HTTP ${res.status}`);
      }
      window.location.reload();
    } catch (e) {
      error = e instanceof Error ? e.message : String(e);
      busy = null;
    }
  }

  async function exitDraft() {
    if (
      pendingCount > 0 &&
      !confirm("Discard pending changes and exit this draft?")
    )
      return;
    store.discardAll();
    await cmsFetch("/session/clear", { method: "POST" });
    try {
      localStorage.removeItem(PREVIEW_LS_KEY);
    } catch {
      /* SSR / quota */
    }
    window.location.reload();
  }

  async function editPreviewVersion() {
    if (!cms.preview) return;
    const res = await cmsFetch("/session/switch", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        branch: cms.preview.branch,
        title: cms.preview.title,
      }),
    });
    const data = (await res.json().catch(() => ({}))) as { pagePath?: string };
    try {
      localStorage.removeItem(PREVIEW_LS_KEY);
    } catch {
      /* SSR */
    }
    const target = data.pagePath;
    if (target && target !== pathname) {
      window.location.href = target;
    } else {
      window.location.reload();
    }
  }

  async function save() {
    if (pendingCount === 0 || !cms.draft) return;
    busy = "saving";
    error = null;
    try {
      // S2 stages text edits only; uploads/folders/deletes arrive with the
      // media phase, so they go up empty for now.
      const res = await cmsFetch("/commit", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({
          edits: store.pendingEdits,
          uploads: [],
          folders: store.pendingFolders,
          deletes: store.pendingDeletes,
        }),
      });
      if (!res.ok) {
        const b = (await res.json().catch(() => ({}))) as { error?: string };
        if (res.status === 401) {
          // A 12h session can lapse mid-edit. Make recovery obvious and reassure
          // that work isn't lost - pending edits are kept on this device and
          // reattach to the next session after logging back in.
          throw new Error(
            "Your session expired - log in again, then your edits are still here. Your unsaved changes are kept on this device.",
          );
        }
        throw new Error(b.error || `Save failed (HTTP ${res.status})`);
      }
      const result = (await res.json()) as {
        direct?: boolean;
        branch?: string;
        prUrl?: string;
        prError?: string;
        branchUrl?: string;
      };
      if (result.direct) {
        // Direct publish: the commit already landed on the live branch. Stay in
        // edit mode (no PR, no preview branch) and confirm inline.
        store.applyCommitted();
        flashNotice(
          `Published - the site redeploys from ${result.branch ?? "the live branch"}`,
        );
        return;
      }
      store.applyCommitted({ prUrl: result.prUrl });
      // Review flow: switch into preview against the just-saved branch so the
      // editor sees the rendered result without the editing outlines.
      if (cms.draft) {
        void store.setPreview({
          branch: cms.draft.branch,
          title: cms.draft.title,
        });
      }
      if (result.prError) {
        error = `Commit succeeded but PR creation failed: ${result.prError}. Branch URL: ${result.branchUrl}`;
      }
    } catch (e) {
      error = e instanceof Error ? e.message : String(e);
    } finally {
      busy = null;
    }
  }

  // The approval lock is a review-flow concept; in direct mode there is no PR
  // to approve, so it must never render (or block saving).
  const approved = $derived(!DIRECT && !!cms.draftApproved);
</script>

{#if !cms.authenticated}
  <!-- ── Login (inline form) ───────────────────────────────────────────── -->
  <form class="cmsbar-login" data-cms-login onsubmit={login}>
    <h2>CMSBar login</h2>
    <input
      type="text"
      placeholder="Username"
      autocomplete="username"
      bind:value={username}
      required
    />
    <input
      type="password"
      placeholder="Password"
      autocomplete="current-password"
      bind:value={password}
      required
    />
    {#if loginError}<p class="cmsbar-login-error">{loginError}</p>{/if}
    <button type="submit" disabled={loginBusy}>
      {loginBusy ? "Signing in…" : "Sign in"}
    </button>
  </form>
{:else if cms.preview}
  <!-- ── Preview banner (review-flow Save lands here) ──────────────────── -->
  <div class="cmsbar-preview-banner" data-cms-preview>
    <span>Previewing draft:</span>
    <strong>{cms.preview.title ?? cms.preview.branch}</strong>
    {#if cms.preview.approved}
      <span class="cmsbar-badge cmsbar-badge-live">approved - read-only</span>
    {/if}
    <button type="button" onclick={() => store.setPreview(null)}>
      Exit preview
    </button>
  </div>
  <div class="cmsbar-bar" data-cms-bar>
    <span class="cmsbar-brand">CMSBar</span>
    <span class="cmsbar-badge cmsbar-badge-preview">Preview</span>
    <span class="cmsbar-divider"></span>
    {#if !cms.preview.approved}
      <button
        type="button"
        class="cmsbar-btn cmsbar-btn-primary"
        onclick={editPreviewVersion}
        title="Switch your active draft to this PR and continue editing it"
      >
        Edit this version
      </button>
    {/if}
    <button
      type="button"
      class="cmsbar-btn"
      onclick={() => store.setPreview(null)}
    >
      Exit preview
    </button>
    <button
      type="button"
      class="cmsbar-btn"
      onclick={() => forkDraft(cms.preview!.branch, cms.preview!.title)}
      title="Create a new draft branched from this one"
    >
      Fork
    </button>
    {#if !DIRECT}
      <button
        type="button"
        class="cmsbar-btn"
        onclick={() => (versionsOpen = true)}
      >
        Versions
      </button>
    {/if}
    <span class="cmsbar-divider"></span>
    <button
      type="button"
      class="cmsbar-btn cmsbar-btn-issues"
      onclick={openIssues}
      title="Report or browse issues for this page"
    >
      🐛 Issues
      {#if issuesCount > 0}<span class="cmsbar-issue-badge">{issuesCount}</span
        >{/if}
    </button>
    <span class="cmsbar-divider"></span>
    <button type="button" class="cmsbar-btn" onclick={logout}>Log out</button>
  </div>
{:else if !cms.draft}
  <!-- ── Live site (no active draft) ───────────────────────────────────── -->
  <div class="cmsbar-bar" data-cms-bar>
    <span class="cmsbar-brand">CMSBar</span>
    <span class="cmsbar-badge cmsbar-badge-live">Live site</span>
    <span class="cmsbar-divider"></span>
    <button
      type="button"
      class="cmsbar-btn cmsbar-btn-primary"
      onclick={startDraft}
      disabled={busy === "starting"}
      title={DIRECT
        ? "Direct publishing: saves commit straight to the live branch"
        : `Will create a draft named "${pageNameForPath(pathname)}"`}
    >
      {busy === "starting" ? "Starting…" : DIRECT ? "Edit site" : "New draft"}
    </button>
    <!-- Versions lists open cms/* PRs; direct publishing creates none, so the
         dialog would be perpetually empty - hide it. -->
    {#if !DIRECT}
      <button
        type="button"
        class="cmsbar-btn"
        onclick={() => (versionsOpen = true)}
      >
        Versions
      </button>
    {/if}
    {#if TOUR_ENABLED}
      <button
        type="button"
        class="cmsbar-btn"
        onclick={openTour}
        title="Replay the guided tour"
      >
        ✦ Guide
      </button>
    {/if}
    <span class="cmsbar-divider"></span>
    <button
      type="button"
      class="cmsbar-btn"
      onclick={() => (metaOpen = true)}
      title="Preview SEO / page metadata (read-only without a draft)"
    >
      🔎 Page meta
    </button>
    <button
      type="button"
      class="cmsbar-btn"
      onclick={() => (settingsOpen = true)}
      title="Preview site settings (read-only without a draft)"
    >
      ⚙️ Settings
    </button>
    <span class="cmsbar-divider"></span>
    <button
      type="button"
      class="cmsbar-btn cmsbar-btn-issues"
      onclick={openIssues}
      title="Report or browse issues for this page"
    >
      🐛 Issues
      {#if issuesCount > 0}<span class="cmsbar-issue-badge">{issuesCount}</span
        >{/if}
    </button>
    <span class="cmsbar-divider"></span>
    <button type="button" class="cmsbar-btn" onclick={logout}>Log out</button>
  </div>
{:else}
  <!-- ── Active draft ──────────────────────────────────────────────────── -->
  <div
    class="cmsbar-strip"
    style={approved
      ? "background: #059669;"
      : DIRECT
        ? "background: #d97706;"
        : undefined}
  >
    <span>
      {approved
        ? "Approved draft (read-only):"
        : DIRECT
          ? "Editing live site:"
          : "Editing draft:"}
    </span>
    <strong>{cms.draft.title}</strong>
    {#if !approved && pendingCount > 0}
      <span class="cmsbar-strip-count">{pendingCount} unsaved</span>
    {/if}
  </div>

  {#if error}
    <div class="cmsbar-error">
      <div class="cmsbar-error-msg">{error}</div>
      <button type="button" onclick={() => (error = null)} aria-label="Dismiss">
        ✕
      </button>
    </div>
  {/if}

  <div class="cmsbar-bar" data-cms-bar>
    <span class="cmsbar-brand">CMSBar</span>
    <span
      class="cmsbar-badge {approved
        ? 'cmsbar-badge-live'
        : DIRECT
          ? 'cmsbar-badge-direct'
          : 'cmsbar-badge-draft'}"
    >
      {approved ? "Approved" : DIRECT ? "Direct" : "Draft"}
    </span>
    <span class="cmsbar-title" title={cms.draft.title}>{cms.draft.title}</span>
    <span class="cmsbar-divider"></span>

    {#if approved}
      <button
        type="button"
        class="cmsbar-btn cmsbar-btn-primary"
        onclick={() => forkDraft(cms.draft!.branch, cms.draft!.title)}
        disabled={busy === "starting"}
        title="This draft is locked - fork it to keep editing"
      >
        {busy === "starting" ? "Forking…" : "Fork"}
      </button>
    {:else}
      <button
        type="button"
        class="cmsbar-btn cmsbar-btn-primary"
        onclick={save}
        disabled={pendingCount === 0 || busy !== null}
        title={pendingCount === 0
          ? "No changes to save"
          : DIRECT
            ? `Publish ${pendingCount} change(s) straight to the live branch`
            : `Save ${pendingCount} change(s)`}
      >
        {busy === "saving"
          ? DIRECT
            ? "Publishing…"
            : "Saving…"
          : DIRECT
            ? "Publish"
            : "Save"}
      </button>
    {/if}
    {#if notice}
      <span class="cmsbar-notice" title={notice}>✓ {notice}</span>
    {/if}

    <button
      type="button"
      class="cmsbar-btn"
      onclick={exitDraft}
      title="Discard this draft and return to the live site"
    >
      Discard draft
    </button>

    <span class="cmsbar-divider"></span>

    <button
      type="button"
      class="cmsbar-btn"
      onclick={() => (metaOpen = true)}
      title={approved
        ? "View SEO / page metadata (read-only)"
        : "Edit SEO / page metadata"}
    >
      🔎 Page meta
    </button>
    <button
      type="button"
      class="cmsbar-btn"
      onclick={() => (settingsOpen = true)}
      title="Site settings"
    >
      ⚙️ Settings
    </button>

    <span class="cmsbar-divider"></span>

    <button
      type="button"
      class="cmsbar-btn cmsbar-btn-issues"
      onclick={openIssues}
      title="Report or browse issues for this page"
    >
      🐛 Issues
      {#if issuesCount > 0}<span class="cmsbar-issue-badge">{issuesCount}</span
        >{/if}
    </button>
    <button
      type="button"
      class="cmsbar-btn"
      class:cmsbar-btn-shared={highlightShared}
      onclick={() => (highlightShared = !highlightShared)}
      title="Highlight every element that appears on more than one page"
    >
      🔗 Shared
    </button>
    {#if TOUR_ENABLED}
      <button
        type="button"
        class="cmsbar-btn"
        onclick={openTour}
        title="Replay the guided tour"
      >
        ✦ Guide
      </button>
    {/if}

    <span class="cmsbar-divider"></span>
    <button type="button" class="cmsbar-btn" onclick={logout}>Log out</button>
  </div>
{/if}

<!-- ── Drawers / panels / tour (rendered for any authenticated state) ────── -->
{#if cms.authenticated}
  {#if versionsOpen}
    <VersionsDialog
      onClose={() => (versionsOpen = false)}
      onFork={(branch, title) => {
        versionsOpen = false;
        forkDraft(branch, title);
      }}
    />
  {/if}
  {#if metaOpen}
    <PageMetaDrawer onClose={() => (metaOpen = false)} canEdit={!!cms.draft && !approved} />
  {/if}
  {#if settingsOpen}
    <SettingsDrawer
      onClose={() => (settingsOpen = false)}
      canEdit={!!cms.draft && !approved}
      highlightShared={highlightShared}
      onToggleHighlight={!!cms.draft && !approved
        ? () => (highlightShared = !highlightShared)
        : undefined}
    />
  {/if}
  {#if issuesOpen}
    <IssuesPanel
      onClose={() => (issuesOpen = false)}
      {pathname}
      {issues}
      loading={issuesLoading && issues.length === 0}
      refreshing={issuesRefreshing}
      error={issuesError}
      reload={reloadIssues}
      {addIssue}
    />
  {/if}
  {#if TOUR_ENABLED}
    <CmsTour />
  {/if}
{/if}

<style>
  /* Issues button badge (the open-count pill, mirroring IssuesButton.tsx). */
  .cmsbar-btn-issues {
    position: relative;
  }
  .cmsbar-issue-badge {
    position: absolute;
    right: -0.375rem;
    top: -0.375rem;
    display: grid;
    place-items: center;
    height: 1rem;
    min-width: 1rem;
    border-radius: 9999px;
    background: var(--cmsbar-accent);
    padding: 0 0.25rem;
    font-size: 9px;
    font-weight: 700;
    color: #fff;
  }
  /* Active shared-highlight toggle. */
  .cmsbar-btn-shared {
    background: var(--cmsbar-shared-soft);
    color: var(--cmsbar-shared-text);
  }
</style>
