// template/components/cmsbar/RichText.tsx
"use client";

import {
  useEffect,
  useRef,
  useState,
  createElement,
  type RefObject,
} from "react";
import { useCms } from "./ContentProvider";
import { Portal } from "./Portal";
import { isSharedPath } from "./shared-paths";
import { cn } from "@/lib/cmsbar/utils";
import { cmsConfig } from "@/cms.config";

type Props = {
  path: string;
  as?: string;
  className?: string;
  fallback?: string;
} & Omit<
  React.HTMLAttributes<HTMLElement>,
  "children" | "onBlur" | "dangerouslySetInnerHTML"
>;

// Optional decorative class the toolbar can toggle on inline spans,
// configured per-project (empty string disables the button entirely).
const HAND_CLASS = cmsConfig.richText?.decorClass ?? "";

// Block-level editor roots get the theme's .cmsbar-prose content defaults
// (headings, lists, links survive Tailwind preflight). Must stay in sync with
// the Toolbar's isBlockRoot check, which gates the block-format buttons.
const BLOCK_TAGS = new Set(["div", "article", "section"]);

function applyClassToSelection(root: HTMLElement, className: string) {
  const sel = window.getSelection();
  if (!sel || sel.rangeCount === 0 || sel.isCollapsed) return;
  const range = sel.getRangeAt(0);
  if (!root.contains(range.commonAncestorContainer)) return;
  const span = document.createElement("span");
  span.className = className;
  try {
    range.surroundContents(span);
  } catch {
    const contents = range.extractContents();
    span.appendChild(contents);
    range.insertNode(span);
  }
  sel.removeAllRanges();
  sel.selectAllChildren(span);
}

function findAncestorWithClass(
  root: HTMLElement,
  className: string,
): HTMLElement | null {
  const sel = window.getSelection();
  if (!sel || sel.rangeCount === 0) return null;
  const range = sel.getRangeAt(0);
  if (!root.contains(range.commonAncestorContainer)) return null;
  let node: Node | null = range.startContainer;
  while (node) {
    if (
      node.nodeType === 1 &&
      (node as HTMLElement).classList?.contains(className)
    ) {
      return node as HTMLElement;
    }
    if (node === root) break;
    node = node.parentNode;
  }
  return null;
}

function findAncestorLink(root: HTMLElement): HTMLAnchorElement | null {
  const sel = window.getSelection();
  if (!sel || sel.rangeCount === 0) return null;
  const range = sel.getRangeAt(0);
  if (!root.contains(range.commonAncestorContainer)) return null;
  let node: Node | null = range.startContainer;
  while (node) {
    if (node.nodeType === 1 && (node as HTMLElement).tagName === "A") {
      return node as HTMLAnchorElement;
    }
    if (node === root) break;
    node = node.parentNode;
  }
  return null;
}

function unwrapElement(el: HTMLElement) {
  const parent = el.parentNode;
  if (!parent) return;
  while (el.firstChild) parent.insertBefore(el.firstChild, el);
  parent.removeChild(el);
}

const ALLOWED_TAGS = new Set([
  "B",
  "I",
  "U",
  "STRONG",
  "EM",
  "BR",
  "SPAN",
  "DIV",
  "P",
  "H1",
  "H2",
  "H3",
  "H4",
  "UL",
  "OL",
  "LI",
  "A",
]);
export function sanitizeRichText(html: string): string {
  return sanitize(html);
}
function sanitize(html: string): string {
  const tpl = document.createElement("template");
  tpl.innerHTML = html;
  const walk = (node: Node) => {
    const children = Array.from(node.childNodes);
    for (const child of children) {
      if (child.nodeType === 1) {
        const el = child as HTMLElement;
        if (!ALLOWED_TAGS.has(el.tagName)) {
          while (el.firstChild) el.parentNode!.insertBefore(el.firstChild, el);
          el.remove();
          continue;
        }
        for (const attr of Array.from(el.attributes)) {
          const keep =
            (el.tagName === "SPAN" && attr.name === "class") ||
            (el.tagName === "A" && attr.name === "href");
          if (!keep) el.removeAttribute(attr.name);
        }
        if (
          el.tagName === "SPAN" &&
          (!HAND_CLASS || el.getAttribute("class") !== HAND_CLASS)
        ) {
          while (el.firstChild) el.parentNode!.insertBefore(el.firstChild, el);
          el.remove();
          continue;
        }
        // Validate and normalise anchor href
        if (el.tagName === "A") {
          const href = el.getAttribute("href") ?? "";
          if (/^https?:/.test(href)) {
            el.setAttribute("target", "_blank");
            el.setAttribute("rel", "noopener noreferrer");
          } else if (!/^(mailto:|\/|#)/.test(href)) {
            // Strip dangerous protocols (javascript:, data:, etc.)
            el.removeAttribute("href");
          }
        }
        walk(el);
      } else if (child.nodeType !== 3 && child.nodeType !== 1) {
        child.parentNode?.removeChild(child);
      }
    }
  };
  walk(tpl.content);
  return tpl.innerHTML;
}

export function RichText({
  path,
  as = "span",
  className,
  fallback,
  ...rest
}: Props) {
  const { get, editMode, cms, addEdit } = useCms();
  const value = (get(path) as string | undefined) ?? fallback ?? "";
  const ref = useRef<HTMLElement | null>(null);
  const [focused, setFocused] = useState(false);
  const isBlock = BLOCK_TAGS.has(as);

  const lastSeenRef = useRef<string>(value);

  useEffect(() => {
    if (!editMode) return;
    if (!ref.current) return;
    if (document.activeElement === ref.current) return;
    // Focus parked in the toolbar (e.g. the link input) means an editing
    // session is live; rewriting innerHTML would detach the saved selection.
    if (document.activeElement?.closest("[data-cms-toolbar]")) return;
    if (ref.current.innerHTML !== value) {
      ref.current.innerHTML = value;
    }
    lastSeenRef.current = value;
  }, [value, editMode]);

  useEffect(() => {
    if (!editMode) return;
    if (!ref.current) return;
    if (ref.current.innerHTML === value) return;
    if (document.activeElement === ref.current) return;
    if (document.activeElement?.closest("[data-cms-toolbar]")) return;
    ref.current.innerHTML = value;
    lastSeenRef.current = value;
  }, [editMode, value]);

  const stage = (nextHtml: string) => {
    const cleaned = sanitize(nextHtml);
    if (cleaned === lastSeenRef.current) return;
    lastSeenRef.current = cleaned;
    addEdit(path, cleaned);
  };

  if (!editMode) {
    return createElement(as, {
      className: isBlock ? cn("cmsbar-prose", className) : className,
      ...rest,
      ...(cms.authenticated && {
        "data-cms-path": path,
        "data-cms-shared": isSharedPath(path) ? "true" : undefined,
      }),
      dangerouslySetInnerHTML: { __html: value },
    });
  }

  const swallow = (e: React.SyntheticEvent) => {
    e.preventDefault();
    e.stopPropagation();
  };

  const editProps: React.HTMLAttributes<HTMLElement> & {
    contentEditable?: boolean;
    suppressContentEditableWarning?: boolean;
    "data-cms-path"?: string;
    "data-cms-shared"?: string;
    ref?: React.Ref<HTMLElement>;
    dangerouslySetInnerHTML?: { __html: string };
  } = {
    ...rest,
    ref,
    contentEditable: true,
    suppressContentEditableWarning: true,
    "data-cms-path": path,
    "data-cms-shared": isSharedPath(path) ? "true" : undefined,
    title: isSharedPath(path)
      ? "Shared element - editing this changes it on every page that uses it"
      : undefined,
    className: cn(
      "outline-none transition-shadow rounded",
      isSharedPath(path)
        ? "ring-2 ring-[var(--cmsbar-shared)] bg-[var(--cmsbar-shared-soft)] hover:ring-[var(--cmsbar-shared-strong)] focus:ring-2 focus:ring-[var(--cmsbar-shared-strong)]"
        : "ring-1 ring-dashed ring-[var(--cmsbar-ring)] hover:ring-[var(--cmsbar-accent)] focus:ring-2 focus:ring-[var(--cmsbar-accent)]",
      "px-0.5",
      isBlock && "cmsbar-prose",
      className,
    ),
    onClickCapture: swallow,
    onFocus: () => {
      setFocused(true);
      try {
        document.execCommand("defaultParagraphSeparator", false, "p");
      } catch {
        /* unsupported on some browsers - harmless */
      }
    },
    onBlur: (e) => {
      // Always stage - even when focus moves into the toolbar (link input).
      // The resync effects above skip while the toolbar holds focus, so
      // staging here can no longer rewrite innerHTML mid-link-edit and
      // detach the toolbar's saved selection range.
      const html = (e.currentTarget as HTMLElement).innerHTML;
      stage(html);
      setTimeout(() => {
        if (document.activeElement?.closest("[data-cms-toolbar]")) return;
        setFocused(false);
      }, 200);
    },
  };

  return (
    <>
      {createElement(as, editProps)}
      {focused && (
        <Portal>
          <Toolbar
            editorRef={ref}
            onAbandon={() => {
              if (ref.current) stage(ref.current.innerHTML);
              setFocused(false);
            }}
          />
        </Portal>
      )}
    </>
  );
}

export function RichTextToolbar({
  editorRef,
  onAbandon,
}: {
  editorRef: RefObject<HTMLElement | null>;
  onAbandon?: () => void;
}) {
  return <Toolbar editorRef={editorRef} onAbandon={onAbandon} />;
}

function Toolbar({
  editorRef,
  onAbandon,
}: {
  editorRef: RefObject<HTMLElement | null>;
  /**
   * Focus left the toolbar for somewhere outside the editor too. The editor's
   * own blur fired earlier (skipped, focus was toolbar-bound) - the host must
   * stage its content now or edits made before opening the panel are lost.
   */
  onAbandon?: () => void;
}) {
  const [pos, setPos] = useState<{ x: number; y: number } | null>(null);
  const [active, setActive] = useState({
    bold: false,
    italic: false,
    underline: false,
    hand: false,
    block: "p",
    ul: false,
    ol: false,
    linkHref: null as string | null, // null = cursor not inside a link
  });

  const [linkOpen, setLinkOpen] = useState(false);
  const [linkHref, setLinkHref] = useState("");
  const linkInputRef = useRef<HTMLInputElement>(null);
  const savedRangeRef = useRef<Range | null>(null);

  const isBlockRoot = (() => {
    const tag = editorRef.current?.tagName;
    return tag === "DIV" || tag === "ARTICLE" || tag === "SECTION";
  })();

  useEffect(() => {
    const updatePos = () => {
      const el = editorRef.current;
      if (!el) return;
      const rect = el.getBoundingClientRect();
      setPos({ x: rect.left + rect.width / 2, y: rect.top });
    };
    const updateActive = () => {
      const root = editorRef.current;
      if (!root) return;
      const sel = window.getSelection();
      if (!sel || sel.rangeCount === 0) return;
      if (!root.contains(sel.getRangeAt(0).commonAncestorContainer)) return;
      const rawBlock = String(document.queryCommandValue("formatBlock") || "")
        .toLowerCase()
        .replace(/[<>]/g, "");
      const block = ["h1", "h2", "h3", "h4", "p"].includes(rawBlock)
        ? rawBlock
        : "p";
      const anchor = findAncestorLink(root);
      setActive({
        bold: document.queryCommandState("bold"),
        italic: document.queryCommandState("italic"),
        underline: document.queryCommandState("underline"),
        hand: !!findAncestorWithClass(root, HAND_CLASS),
        block,
        ul: document.queryCommandState("insertUnorderedList"),
        ol: document.queryCommandState("insertOrderedList"),
        linkHref: anchor ? (anchor.getAttribute("href") ?? "") : null,
      });
    };
    updatePos();
    updateActive();
    document.addEventListener("selectionchange", updateActive);
    window.addEventListener("scroll", updatePos, true);
    window.addEventListener("resize", updatePos);
    return () => {
      document.removeEventListener("selectionchange", updateActive);
      window.removeEventListener("scroll", updatePos, true);
      window.removeEventListener("resize", updatePos);
    };
  }, [editorRef]);

  const exec = (cmd: string, value?: string) => {
    const root = editorRef.current;
    if (!root) return;
    root.focus();
    try {
      document.execCommand("styleWithCSS", false, "false");
    } catch {
      /* not supported */
    }
    document.execCommand(cmd, false, value);
  };

  const setBlock = (tag: "p" | "h2" | "h3" | "h4") =>
    exec("formatBlock", `<${tag}>`);

  const toggleHand = () => {
    const root = editorRef.current;
    if (!root) return;
    root.focus();
    const sel = window.getSelection();
    const collapsed = !sel || sel.rangeCount === 0 || sel.isCollapsed;
    const ancestor = findAncestorWithClass(root, HAND_CLASS);
    if (ancestor === root) return;
    if (ancestor) {
      unwrapElement(ancestor);
    } else if (!collapsed) {
      applyClassToSelection(root, HAND_CLASS);
    }
    setActive((a) => ({ ...a, hand: !a.hand }));
  };

  const openLink = () => {
    const root = editorRef.current;
    if (!root) return;
    const sel = window.getSelection();
    if (sel && sel.rangeCount > 0) {
      savedRangeRef.current = sel.getRangeAt(0).cloneRange();
    }
    const currentHref = active.linkHref ?? "";
    setLinkHref(currentHref);
    setLinkOpen((prev) => {
      if (!prev) setTimeout(() => linkInputRef.current?.focus(), 50);
      return !prev;
    });
  };

  const applyLink = () => {
    const href = linkHref.trim();
    if (!href) return;
    const root = editorRef.current;
    if (!root) return;

    // If a re-render rewrote the editor's innerHTML since the range was
    // saved, its nodes are detached; restoring it would give a collapsed
    // selection and silently skip createLink. Close the panel instead.
    if (
      savedRangeRef.current &&
      !savedRangeRef.current.startContainer.isConnected
    ) {
      setLinkOpen(false);
      return;
    }

    root.focus();
    const sel = window.getSelection();
    if (sel && savedRangeRef.current) {
      sel.removeAllRanges();
      sel.addRange(savedRangeRef.current);
    }

    const existingAnchor = findAncestorLink(root);
    if (existingAnchor) {
      existingAnchor.setAttribute("href", href);
      if (href.startsWith("http")) {
        existingAnchor.setAttribute("target", "_blank");
        existingAnchor.setAttribute("rel", "noopener noreferrer");
      } else {
        existingAnchor.removeAttribute("target");
        existingAnchor.removeAttribute("rel");
      }
    } else if (savedRangeRef.current && !savedRangeRef.current.collapsed) {
      exec("createLink", href);
      const newAnchor = findAncestorLink(root);
      if (newAnchor && href.startsWith("http")) {
        newAnchor.setAttribute("target", "_blank");
        newAnchor.setAttribute("rel", "noopener noreferrer");
      }
    }

    setLinkOpen(false);
  };

  const removeLink = () => {
    exec("unlink");
    setLinkOpen(false);
  };

  if (!pos) return null;

  const btn = "px-2 py-1 text-xs font-medium rounded hover:bg-white/10";
  const activeCls =
    "bg-[var(--cmsbar-accent)] text-white hover:bg-[var(--cmsbar-accent)]";
  const top = Math.max(8, pos.y - 44);

  return (
    <div
      data-cms-toolbar
      style={{
        position: "fixed",
        left: pos.x,
        top,
        transform: "translateX(-50%)",
      }}
      className="z-[120] flex flex-col rounded-lg bg-slate-900/95 text-white shadow-lg backdrop-blur"
      onMouseDown={(e) => e.preventDefault()}
      onBlur={(e) => {
        // Focus left the toolbar (link input / tab-out) for somewhere outside
        // the editor: the editing session is over. Close the panel and let
        // the host stage + dismiss, instead of orphaning a floating toolbar.
        const next = e.relatedTarget as HTMLElement | null;
        const root = editorRef.current;
        if (
          next &&
          (e.currentTarget.contains(next) ||
            next === root ||
            root?.contains(next))
        ) {
          return;
        }
        setLinkOpen(false);
        onAbandon?.();
      }}
    >
      <div className="flex items-center gap-0.5 px-1 py-1">
        <button
          type="button"
          className={cn(btn, "font-bold", active.bold && activeCls)}
          onClick={() => exec("bold")}
          title="Bold (Cmd/Ctrl+B)"
        >
          B
        </button>
        <button
          type="button"
          className={cn(btn, "italic", active.italic && activeCls)}
          onClick={() => exec("italic")}
          title="Italic (Cmd/Ctrl+I)"
        >
          I
        </button>
        <button
          type="button"
          className={cn(btn, "underline", active.underline && activeCls)}
          onClick={() => exec("underline")}
          title="Underline (Cmd/Ctrl+U)"
        >
          U
        </button>
        {HAND_CLASS && (
          <>
            <span className="mx-1 h-4 w-px bg-white/20" />
            <button
              type="button"
              className={cn(
                btn,
                HAND_CLASS,
                "text-base",
                active.hand && activeCls,
              )}
              onClick={toggleHand}
              title="Toggle hand-font on selection"
            >
              Hand
            </button>
          </>
        )}
        {isBlockRoot && (
          <>
            <span className="mx-1 h-4 w-px bg-white/20" />
            <button
              type="button"
              className={cn(btn, active.block === "p" && activeCls)}
              onClick={() => setBlock("p")}
              title="Paragraph"
            >
              P
            </button>
            <button
              type="button"
              className={cn(
                btn,
                "font-bold",
                active.block === "h2" && activeCls,
              )}
              onClick={() => setBlock("h2")}
              title="Heading 2"
            >
              H2
            </button>
            <button
              type="button"
              className={cn(
                btn,
                "font-bold",
                active.block === "h3" && activeCls,
              )}
              onClick={() => setBlock("h3")}
              title="Heading 3"
            >
              H3
            </button>
            <button
              type="button"
              className={cn(
                btn,
                "font-bold",
                active.block === "h4" && activeCls,
              )}
              onClick={() => setBlock("h4")}
              title="Heading 4"
            >
              H4
            </button>
            <span className="mx-1 h-4 w-px bg-white/20" />
            <button
              type="button"
              className={cn(btn, active.ul && activeCls)}
              onClick={() => exec("insertUnorderedList")}
              title="Bulleted list"
            >
              • List
            </button>
            <button
              type="button"
              className={cn(btn, active.ol && activeCls)}
              onClick={() => exec("insertOrderedList")}
              title="Numbered list"
            >
              1. List
            </button>
          </>
        )}
        <span className="mx-1 h-4 w-px bg-white/20" />
        <button
          type="button"
          className={cn(btn, "text-white/70")}
          onClick={() => exec("removeFormat")}
          title="Clear formatting"
        >
          Clear
        </button>
        <span className="mx-1 h-4 w-px bg-white/20" />
        <button
          type="button"
          className={cn(
            btn,
            (active.linkHref !== null || linkOpen) && activeCls,
          )}
          onClick={openLink}
          title={
            active.linkHref !== null ? "Edit link" : "Add link to selection"
          }
        >
          Link
        </button>
      </div>

      {linkOpen && (
        <div className="flex items-center gap-1 border-t border-white/20 px-2 py-1.5">
          <input
            ref={linkInputRef}
            type="url"
            value={linkHref}
            onChange={(e) => setLinkHref(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter") {
                e.preventDefault();
                applyLink();
              }
              if (e.key === "Escape") {
                e.preventDefault();
                // Refocus the editor BEFORE the input unmounts - an element
                // removed while focused fires no blur, which would orphan the
                // toolbar and skip the container's abandon handling.
                editorRef.current?.focus();
                setLinkOpen(false);
              }
            }}
            onMouseDown={(e) => e.stopPropagation()}
            placeholder="https://..."
            className="min-w-[220px] flex-1 rounded bg-slate-800 px-2 py-1 text-xs text-white outline-none focus:ring-1 focus:ring-[var(--cmsbar-accent)]"
          />
          <button
            type="button"
            className={cn(
              btn,
              "bg-[var(--cmsbar-accent)] text-white hover:bg-[var(--cmsbar-accent-strong)]",
            )}
            onClick={applyLink}
          >
            Apply
          </button>
          {active.linkHref !== null && (
            <button
              type="button"
              className={cn(btn, "text-red-400 hover:text-red-300")}
              onClick={removeLink}
            >
              Remove
            </button>
          )}
        </div>
      )}
    </div>
  );
}

// examples/sveltekit/src/cmsbar/RichText.svelte
<script lang="ts" module>
  // Block-level editor roots get the theme's .cmsbar-prose content defaults
  // (headings, lists, links survive a CSS reset). Must stay in sync with the
  // Toolbar's isBlockRoot check, which gates the block-format buttons.
  const BLOCK_TAGS = new Set(["div", "article", "section"]);

  // ── Selection/Range helpers, ported verbatim from RichText.tsx ──────────────

  export function applyClassToSelection(root: HTMLElement, className: string) {
    const sel = window.getSelection();
    if (!sel || sel.rangeCount === 0 || sel.isCollapsed) return;
    const range = sel.getRangeAt(0);
    if (!root.contains(range.commonAncestorContainer)) return;
    const span = document.createElement("span");
    span.className = className;
    try {
      range.surroundContents(span);
    } catch {
      const contents = range.extractContents();
      span.appendChild(contents);
      range.insertNode(span);
    }
    sel.removeAllRanges();
    sel.selectAllChildren(span);
  }

  export function findAncestorWithClass(
    root: HTMLElement,
    className: string,
  ): HTMLElement | null {
    const sel = window.getSelection();
    if (!sel || sel.rangeCount === 0) return null;
    const range = sel.getRangeAt(0);
    if (!root.contains(range.commonAncestorContainer)) return null;
    let node: Node | null = range.startContainer;
    while (node) {
      if (
        node.nodeType === 1 &&
        (node as HTMLElement).classList?.contains(className)
      ) {
        return node as HTMLElement;
      }
      if (node === root) break;
      node = node.parentNode;
    }
    return null;
  }

  export function findAncestorLink(root: HTMLElement): HTMLAnchorElement | null {
    const sel = window.getSelection();
    if (!sel || sel.rangeCount === 0) return null;
    const range = sel.getRangeAt(0);
    if (!root.contains(range.commonAncestorContainer)) return null;
    let node: Node | null = range.startContainer;
    while (node) {
      if (node.nodeType === 1 && (node as HTMLElement).tagName === "A") {
        return node as HTMLAnchorElement;
      }
      if (node === root) break;
      node = node.parentNode;
    }
    return null;
  }

  export function unwrapElement(el: HTMLElement) {
    const parent = el.parentNode;
    if (!parent) return;
    while (el.firstChild) parent.insertBefore(el.firstChild, el);
    parent.removeChild(el);
  }
</script>

<script lang="ts">
  // Inline rich-text editing, ported from template/components/cmsbar/RichText.tsx
  // to Svelte 5. View mode renders the saved (sanitized) HTML inert; edit mode
  // turns the same element into a contenteditable region with a floating
  // selection toolbar (h2/h3/h4, bold, italic, underline, lists, link, plus an
  // optional decorative-class button when cmsConfig.richText.decorClass is set).
  //
  // The toolbar drives the browser's execCommand + Selection/Range API exactly
  // as the React original does, then stages sanitized HTML through the store's
  // addEdit(path, ...). The same caret-preservation rule as T.svelte applies:
  // the value->DOM sync writes innerHTML only when the editor is NOT focused (and
  // focus is not parked in the toolbar's link input), so a re-render mid-edit
  // never detaches the saved selection or collapses the caret.
  //
  // The toolbar is rendered through a Svelte portal (node relocated to <body>),
  // mirroring the React <Portal>, so position:fixed coordinates are viewport-
  // relative and the panel escapes any overflow-clipping ancestor.

  import { getCmsContext } from "@/cmsbar/content.svelte";
  import { isSharedPath } from "@/lib/cmsbar/shared-paths";
  import { cmsConfig } from "@/cms.config";
  import { sanitizeRichText } from "@/cmsbar/richText";
  import Toolbar from "@/cmsbar/RichTextToolbar.svelte";

  type Props = {
    path: string;
    as?: string;
    class?: string;
    fallback?: string;
  };

  let { path, as = "span", class: className, fallback = "" }: Props = $props();

  // Optional decorative class the toolbar can toggle on inline spans (empty
  // string disables the button entirely), configured per-project.
  const HAND_CLASS = cmsConfig.richText?.decorClass ?? "";

  const store = getCmsContext();

  const value = $derived((store.get(path) as string | undefined) ?? fallback);
  const editMode = $derived(store.editMode);
  const authenticated = $derived(store.cms.authenticated);
  const shared = $derived(isSharedPath(path));
  const isBlock = $derived(BLOCK_TAGS.has(as));

  let el = $state<HTMLElement | null>(null);
  let focused = $state(false);

  // Tracks the last HTML we either seeded or staged, so stage() can no-op when
  // nothing meaningful changed (mirrors lastSeenRef in RichText.tsx). Seeded by
  // the value->DOM effect below on mount; this is just the starting sentinel.
  let lastSeen = "";

  function stage(nextHtml: string) {
    const cleaned = sanitizeRichText(nextHtml, HAND_CLASS);
    if (cleaned === lastSeen) return;
    lastSeen = cleaned;
    store.addEdit(path, cleaned);
  }

  // value -> DOM sync (edit mode only). Writes innerHTML ONLY when the editor is
  // not focused and focus is not parked in the toolbar (the link input keeps a
  // live editing session whose saved Range we must not detach). Faithful copy of
  // the two RichText.tsx resync effects, collapsed into one.
  $effect(() => {
    const node = el;
    const next = value;
    if (!node) return;
    if (!editMode) return;
    if (typeof document === "undefined") return;
    if (document.activeElement === node) return;
    if (document.activeElement?.closest("[data-cms-toolbar]")) return;
    if (node.innerHTML !== next) node.innerHTML = next;
    lastSeen = next;
  });

  function onFocus() {
    focused = true;
    try {
      document.execCommand("defaultParagraphSeparator", false, "p");
    } catch {
      /* unsupported on some browsers - harmless */
    }
  }

  function onBlur(e: FocusEvent) {
    // Always stage - even when focus moves into the toolbar (link input). The
    // resync effect above skips while the toolbar holds focus, so staging here
    // can no longer rewrite innerHTML mid-link-edit and detach the saved range.
    const html = (e.currentTarget as HTMLElement).innerHTML;
    stage(html);
    setTimeout(() => {
      if (document.activeElement?.closest("[data-cms-toolbar]")) return;
      focused = false;
    }, 200);
  }

  function swallow(e: Event) {
    e.preventDefault();
    e.stopPropagation();
  }

  function onAbandon() {
    if (el) stage(el.innerHTML);
    focused = false;
  }
</script>

{#if editMode}
  <svelte:element
    this={as}
    bind:this={el}
    data-cms-path={path}
    data-cms-shared={shared ? "true" : undefined}
    title={shared
      ? "Shared element - editing this changes it on every page that uses it"
      : undefined}
    class={[
      "cmsbar-richtext",
      shared && "cmsbar-richtext-shared",
      isBlock && "cmsbar-prose",
      className,
    ]}
    contenteditable="true"
    role="textbox"
    tabindex="0"
    onfocus={onFocus}
    onblur={onBlur}
    onclickcapture={swallow}
  ></svelte:element>
  {#if focused && el}
    <Toolbar editor={el} handClass={HAND_CLASS} {onAbandon} />
  {/if}
{:else}
  <svelte:element
    this={as}
    data-cms-path={authenticated ? path : undefined}
    data-cms-shared={authenticated && shared ? "true" : undefined}
    class={[isBlock && "cmsbar-prose", className]}
  >{@html value}</svelte:element>
{/if}

<style>
  /* Edit-mode outline, mirroring RichText.tsx's ring treatment. The amber
     "shared" variant warns about site-wide content. */
  .cmsbar-richtext {
    outline: none;
    border-radius: 4px;
    padding: 0 2px;
    box-shadow: 0 0 0 1px var(--cmsbar-ring);
    transition: box-shadow 0.15s ease;
  }
  .cmsbar-richtext:hover {
    box-shadow: 0 0 0 1px var(--cmsbar-accent);
  }
  .cmsbar-richtext:focus {
    box-shadow: 0 0 0 2px var(--cmsbar-accent);
  }
  .cmsbar-richtext-shared {
    background: var(--cmsbar-shared-soft);
    box-shadow: 0 0 0 2px var(--cmsbar-shared);
  }
  .cmsbar-richtext-shared:hover,
  .cmsbar-richtext-shared:focus {
    box-shadow: 0 0 0 2px var(--cmsbar-shared-strong);
  }
</style>
