// examples/sveltekit/src/routes/+page.svelte
<script lang="ts">
  // Renders the CMS content model in Svelte. The eyebrow + SEO head come from
  // +page.server.ts (getContent() on the server). The editable fields render
  // through <T>, which resolves each path from the CMSBar store: for anonymous
  // visitors that is the same bundled content, in the SSR HTML and inert; for a
  // logged-in editor with an active draft the same elements become editable in
  // place (contenteditable), and typing stages edits the bar can Save.
  import type { PageData } from "./$types";
  import T from "@/cmsbar/T.svelte";
  import EditableImage from "@/cmsbar/EditableImage.svelte";
  import EditableMedia from "@/cmsbar/EditableMedia.svelte";

  let { data }: { data: PageData } = $props();
</script>

<svelte:head>
  <title>{data.meta.title}</title>
  <meta name="description" content={data.meta.description} />
  <meta property="og:title" content={data.meta.ogTitle} />
  <meta property="og:description" content={data.meta.ogDescription} />
  {#if data.meta.ogImage}
    <meta property="og:image" content={data.meta.ogImage} />
  {/if}
  {#if data.meta.canonical}
    <link rel="canonical" href={data.meta.canonical} />
  {/if}
  {#if data.meta.robots}
    <meta name="robots" content="noindex, nofollow" />
  {/if}
</svelte:head>

<main>
  <p class="eyebrow">{data.siteName}</p>
  <T as="h1" path="demo.title" />
  <T as="p" path="demo.intro" />

  <!-- EditableImage: object-cover fill, so editors can drag the focal point.
       The positioned wrapper gives the absolutely-filled <img> a box. -->
  <figure class="demo-image">
    <EditableImage path="demo.image" alt="CMSBar demo image" fill />
  </figure>

  <!-- EditableMedia: image / video / embed in one slot. The positioned wrapper
       gives the absolutely-filled media a 16:9 box. -->
  <div class="demo-media">
    <EditableMedia path="demo.media" />
  </div>
</main>

<style>
  .demo-image {
    position: relative;
    margin: 2rem 0 0;
    width: 100%;
    aspect-ratio: 1200 / 630;
    border-radius: 0.75rem;
    overflow: hidden;
  }
  .demo-media {
    position: relative;
    margin: 1.5rem 0 0;
    width: 100%;
    aspect-ratio: 16 / 9;
    border-radius: 0.75rem;
    overflow: hidden;
    background: #0f172a;
  }
</style>

// examples/tanstack-start/src/routes/index.tsx
// Demo home page. Renders editable content through the framework-neutral CMS
// primitives (<T> for text, <EditableImage> for the hero) - the exact same
// components the Next and React Router examples use, driven here by the
// TanStack Start host seam.
//
// The route `head` is built from the CMS-editable page metadata: resolvePageMeta
// (neutral) merges the "home" pageMeta entry over a hardcoded fallback, and we
// map that plain object onto TanStack Router head descriptors.

import { createFileRoute } from "@tanstack/react-router";
import { T } from "@/components/cmsbar/T";
import { EditableImage } from "@/components/cmsbar/EditableImage";
import { resolvePageMeta } from "@/lib/cmsbar/page-meta-core";
import { getPageMeta } from "@/lib/cmsbar/page-meta";

export const Route = createFileRoute("/")({
  head: () => {
    const resolved = resolvePageMeta(getPageMeta("home"), {
      title: "CMSBar runs in this TanStack Start host",
      description: "A site edited in place with CMSBar.",
    });

    const meta: Array<Record<string, string>> = [
      { title: resolved.title },
      { name: "description", content: resolved.description },
      { property: "og:title", content: resolved.ogTitle },
      { property: "og:description", content: resolved.ogDescription },
    ];
    if (resolved.ogImage) {
      meta.push({ property: "og:image", content: resolved.ogImage });
    }
    if (resolved.robots) {
      meta.push({ name: "robots", content: "noindex, nofollow" });
    }

    const links: Array<Record<string, string>> = [];
    if (resolved.canonical) {
      links.push({ rel: "canonical", href: resolved.canonical });
    }

    return { meta, links };
  },
  component: Home,
});

function Home() {
  return (
    <main
      style={{
        maxWidth: 760,
        margin: "0 auto",
        padding: "48px 24px",
        fontFamily: "system-ui, sans-serif",
      }}
    >
      <T as="h1" path="demo.title" />
      <T as="p" path="demo.intro" />
      <div
        style={{
          position: "relative",
          width: "100%",
          aspectRatio: "1200 / 630",
          marginTop: 24,
          borderRadius: 12,
          overflow: "hidden",
        }}
      >
        <EditableImage
          path="demo.image"
          alt="CMSBar demo"
          fill
          sizes="(max-width: 760px) 100vw, 760px"
        />
      </div>
    </main>
  );
}
